### PR TITLE
Connections 

### PR DESCRIPTION
**Pull request by breznak**
- fixes Timer to return precise results 553c8fc 
- please review my "fix" for test 5e18b6f
- tried to see why the serialization test is failing..I don't know

### CODE REVIEW

**Comment by breznak** [comment]
@ctrl-z-9000-times please review my progress

**Comment by ctrl-z-9000-times** [comment]
I know why serialization is failing and have a fix for it. Will upload soon...

**Comment by ctrl-z-9000-times** [comment]
Where did  src/test/unit/algorithms/Serialization.cpp go?

**Comment by ctrl-z-9000-times** [comment]
I like the improved timer!

**Comment by breznak** [comment]
> Where did src/test/unit/algorithms/Serialization.cpp go? 

There were only 2 tests (which had a similar test in their other classes anyway), so I've decided we keep adding tests to all classes implementing Serializable: ie SpatialPoolerTest::testSaveLoad, etc. 

Tests from Serialization.cpp were moved to RandomTest, SpatialPoolerTest

**Comment by ctrl-z-9000-times** [comment]
But I don't think that there is an "... _A" variant.  I thought there was just one version of each of those tests.  Also: in the logs the name of the group of tests is included, in this case: "SpatialPoolerTest".  So that makes these tests unique to this file.

**Comment by breznak** [comment]
> But I don't think that there is an "... _A" variant. I thought there was just one version of each of those tests. Also: in the logs the name of the group of tests is included, in this case: "SpatialPoolerTest". So that makes these tests unique to this file. 

no, there are 2 tests in SpatialPoolerTest with the same name, see 
https://github.com/ctrl-z-9000-times/nupic.cpp/pull/6/files#diff-7b7cf55c95878a95b2a8d57d63d94f81R1780

https://github.com/ctrl-z-9000-times/nupic.cpp/pull/6/files#diff-7b7cf55c95878a95b2a8d57d63d94f81R1808 

The difference is one parameter being changed,3 vs 1. Hence the names _Atleast3Active, _B 

The same is for Local/Global inhibition version of that test.

**Comment by ctrl-z-9000-times** [comment]
I think you misread the method names:
`ZeroOverlap_NoStimulusThreshold_LocalInhibition`
`ZeroOverlap_StimulusThreshold_LocalInhibition`

**Comment by breznak** [comment]
> you misread the method names: 

my bad! sorry. Fixing.. Thanks for catching that

**Comment by ctrl-z-9000-times** [comment]
Looks good, thank you @breznak !

**Pull request merged**
